name: Verify Amplify Setup

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run verification script
        run: bash scripts/verify_amplify_setup.sh
